import '@/assets/styles/styles.scss'
import type { Metadata } from 'next'
import {font} from "@/assets/fonts/fonts";
import Layout from "@/components/layout/layout";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Layout>
          {children}
        </Layout>
      </body>
    </html>
  )
}
